kyverno/policy-reporter-ui

- README.md
- go.mod
- main.go
- pkg/api/handler.go
Signed-off-by: Frank Jogeleit <fj@move-elevator.de>
> update repository owner

- frontend/src/components/ClusterPolicyTable.vue
- frontend/src/components/PolicyTable.vue
Signed-off-by: Frank Jogeleit <fj@move-elevator.de>
> hide rule chip if empty

- Makefile
- frontend/.eslintrc.js
- frontend/src/App.vue
- frontend/src/api.ts
- frontend/src/components/PolicyAutocomplete.vue
- frontend/src/plugins/kyverno/api.ts
- frontend/src/plugins/kyverno/components/PolicyTable.vue
- frontend/src/plugins/kyverno/views/Details.vue
- frontend/src/router/index.ts
- frontend/src/subpath.ts
- frontend/vue.config.js
Signed-off-by: Frank Jogeleit <fj@move-elevator.de>
> Using relativ publicPath for SubPath support

- Dockerfile
Relates to https://github.com/kyverno/policy-reporter-kyverno-plugin/issues/8.
> Update Golang base image to 1.17.2

- .eslintrc.js
- components/ClusterPolicyReportTable.vue
- components/PolicyReportTable.vue
- components/charts/ClusterPolicyStatus.vue
- components/charts/PolicyStatusPerNamespace.vue
- package-lock.json
- package.json
- policy-reporter-plugins/core/mapper.ts
> Fix: show Properties in result tables

- components/AppNavigation.vue
- components/AppNavigationGroup.vue
- components/AppNavigationItem.vue
- pages/kyverno-plugin/verify-image-rules/index.vue
- policy-reporter-plugins/kyverno/api.ts
- policy-reporter-plugins/kyverno/components/AttestationsDialog.vue
- policy-reporter-plugins/kyverno/components/VerifyImageTable.vue
- policy-reporter-plugins/kyverno/types.ts
> Add VerifyImages view

- .gitignore
- components/AppNavigation.vue
- layouts/default.vue
- pages/kyverno-plugin/_uid/index.vue
- pages/kyverno-plugin/index.vue
- pages/kyverno-plugin/verify-image-rules/index.vue
- policy-reporter-plugins/core/api.ts
- policy-reporter-plugins/core/types.ts
- server/pkg/config/config.go
> Add configs to disable/enabled views

- layouts/default.vue
- pages/index.vue
- policy-reporter-plugins/core/api.ts
- policy-reporter-plugins/core/types.ts
- server/pkg/config/config.go
- store/index.ts
Signed-off-by: Frank Jogeleit <frank.jogeleit@lovoo.com>
> Dashboard: Disable PolicyReports or ClusterPolicyReports

- Makefile
- policy-reporter-plugins/core/api.ts
> Update sources filter

- Dockerfile
> Bump Go to 1.17.8

- helper/layouthHelper.ts
- pages/cluster-policy-reports/_source/index.vue
- pages/cluster-policy-reports/index.vue
- pages/policy-reports/_source/index.vue
- pages/policy-reports/index.vue
> Update graphsizing depending on result status

- components/ClusterPolicyReportTable.vue
- components/PolicyReportTable.vue
- components/selects/SearchField.vue
- helper/layouthHelper.ts
- policy-reporter-plugins/core/api.ts
- policy-reporter-plugins/core/types.ts
> Add serverside pagination for result tables

- .github/workflows/image.yaml
- Dockerfile
- Makefile
> Update Image Workflow

- Makefile
- server/go.mod
- server/go.sum
- server/main.go
- server/pkg/api/handler.go
- server/pkg/config/config.go
- server/pkg/redis/store.go
- server/pkg/report/store.go
> Add Redis as external log storage

- server/main.go
- server/pkg/proxy/proxy.go
Fixes: https://github.com/kyverno/policy-reporter/issues/177
> Improve ReverseProxy to overwrite request Host

- components/selects/CategoryAutocomplete.vue
- components/selects/PolicyAutocomplete.vue
> Fix Select data propagation

- components/chips/SeverityChip.vue
- components/chips/StatusChip.vue
- components/selects/SeverityAutocomplete.vue
- policy-reporter-plugins/core/mapper.ts
- policy-reporter-plugins/core/types.ts
> Add new Severity values

- components/AppNavigation.vue
- components/ClusterPolicyReportTable.vue
- components/PolicyReportTable.vue
- components/charts/FailingClusterPolicies.vue
- components/selects/CategoryAutocomplete.vue
- components/selects/KindAutocomplete.vue
- components/selects/NamespaceAutocomplete.vue
- components/selects/PolicyAutocomplete.vue
- components/selects/RefreshIntervalSelect.vue
- layouts/default.vue
- package-lock.json
- pages/cluster-policy-reports/_source/index.vue
- pages/index.vue
- pages/kyverno-plugin/_uid/index.vue
- pages/kyverno-plugin/index.vue
- pages/kyverno-plugin/verify-image-rules/index.vue
- pages/logs/index.vue
- pages/policy-reports/_source/index.vue
- pages/policy-reports/index.vue
- policy-reporter-plugins/core/api.ts
- policy-reporter-plugins/core/types.ts
- server/pkg/config/config.go
#174 
Add a disable option and make the default interval configurable.
> Configurable default refreshInterval and disable option

- components/ClusterPolicyReportTable.vue
- components/LabelFilterRow.vue
- components/PolicyReportTable.vue
- components/selects/LabelFilter.vue
- layouts/default.vue
- pages/cluster-policy-reports/_source/index.vue
- pages/cluster-policy-reports/index.vue
- pages/policy-reports/_source/index.vue
- pages/policy-reports/index.vue
- policy-reporter-plugins/core/api.ts
- policy-reporter-plugins/core/types.ts
- server/pkg/config/config.go
- store/index.ts
> Implement Label Filter

- components/AppNavigation.vue
- components/selects/NamespaceAutocomplete.vue
- components/selects/PolicyAutocomplete.vue
- pages/kyverno-plugin/_uid/index.vue
- pages/kyverno-plugin/index.vue
- policy-reporter-plugins/kyverno/api.ts
- policy-reporter-plugins/kyverno/components/ReporTypeSelect.vue
- policy-reporter-plugins/kyverno/components/ReportButton.vue
- policy-reporter-plugins/kyverno/components/ReportDialog.vue
- policy-reporter-plugins/kyverno/types.ts
> Implement Kyverno Compliance Reports

- Dockerfile
Signed-off-by: fsl <1171313930@qq.com>
> fix golang:1.19 vulnerability and add TARGETARCH parameter

- Makefile
- components/ClusterPolicyReportTable.vue
- components/PolicyReportTable.vue
- package.json
> Don't hide columes without results

- server/pkg/proxy/proxy.go
Signed-off-by: fsl <1171313930@qq.com>
> update deprecated Dial to DialContext

- server/go.mod
- server/go.sum
Signed-off-by: fsl <1171313930@qq.com>
> bump golang.org/x/text from 0.5.0 to 0.6.0

- server/main.go
- server/pkg/config/config.go
- server/pkg/proxy/proxy.go
#159 
Support SkipTLS or custom CA for HTTP Proxy
> Support SkipTLS or custom Certificate for external APIs

- server/main.go
- server/pkg/proxy/proxy.go
https://github.com/kyverno/policy-reporter/issues/288
> Add flag to enable/disable proxy request host overwrite

- backend/pkg/config/config.go
- backend/pkg/config/mapper.go
- backend/pkg/server/api/handler.go
- backend/pkg/server/api/model.go
The goal is to add the simple possibility to allow explicitly users accessing to custom boards with a list of user emails in the config file.
> Feat: Adding basic feature for user management

- backend/pkg/auth/permissions.go
- backend/pkg/config/config.go
- backend/pkg/config/mapper.go
- backend/pkg/config/resolver.go
- backend/pkg/server/api/handler.go
- backend/pkg/server/api/model.go
- frontend/modules/core/components/form/ClusterSelect.vue
https://github.com/kyverno/policy-reporter/issues/486
> Cluster permissions

- backend/go.mod
- backend/go.sum
- backend/pkg/auth/handler.go
- backend/pkg/auth/helper.go
- backend/pkg/auth/middleware.go
- backend/pkg/auth/redis.go
- backend/pkg/auth/router.go
- backend/pkg/config/config.go
- backend/pkg/config/resolver.go
add redis as alternative session storage
> add redis store

- backend/pkg/config/config.go
- backend/pkg/kubernetes/secrets/client.go
Add support to import CallbackURL from a secret.
> Add support to import CallbackURL from Secret
